name: CI

on:
  push:
    branches: [ main, trunk, master, "**" ]  # adjust as needed
  pull_request:

env:
  TMPDIR: ${{ github.workspace }}/tmp
  GOTMPDIR: ${{ github.workspace }}/tmp
  CGO_ENABLED: 1
  GO111MODULE: on

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Free up disk space
      run: |
        sudo rm -rf /usr/share/dotnet
        sudo rm -rf /opt/ghc
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"

    - name: Ensure tmp dir exists
      run: mkdir -p ./tmp

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'  # or whatever version you're using

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y make gcc

    - name: Run tests
      run: make test
